# ปิด Jekyll processing

plugins: []
markdown: kramdown
kramdown:
smart_quotes: [“apos”, “apos”, “quot”, “quot”]
typographic_symbols:
mdash: ‘–’
ndash: ‘–’
ellipsis: ‘…’
laquo_space: ‘<< ’
raquo_space: ’ >>’
